// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: elys/commitment/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryShowCommitmentsRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryShowCommitmentsRequest) Reset()         { *m = QueryShowCommitmentsRequest{} }
func (m *QueryShowCommitmentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowCommitmentsRequest) ProtoMessage()    {}
func (*QueryShowCommitmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{2}
}
func (m *QueryShowCommitmentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowCommitmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowCommitmentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowCommitmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowCommitmentsRequest.Merge(m, src)
}
func (m *QueryShowCommitmentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowCommitmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowCommitmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowCommitmentsRequest proto.InternalMessageInfo

func (m *QueryShowCommitmentsRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryShowCommitmentsResponse struct {
	Commitments Commitments `protobuf:"bytes,1,opt,name=commitments,proto3" json:"commitments"`
}

func (m *QueryShowCommitmentsResponse) Reset()         { *m = QueryShowCommitmentsResponse{} }
func (m *QueryShowCommitmentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowCommitmentsResponse) ProtoMessage()    {}
func (*QueryShowCommitmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{3}
}
func (m *QueryShowCommitmentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowCommitmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowCommitmentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowCommitmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowCommitmentsResponse.Merge(m, src)
}
func (m *QueryShowCommitmentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowCommitmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowCommitmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowCommitmentsResponse proto.InternalMessageInfo

func (m *QueryShowCommitmentsResponse) GetCommitments() Commitments {
	if m != nil {
		return m.Commitments
	}
	return Commitments{}
}

type QueryNumberOfCommitmentsRequest struct {
}

func (m *QueryNumberOfCommitmentsRequest) Reset()         { *m = QueryNumberOfCommitmentsRequest{} }
func (m *QueryNumberOfCommitmentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNumberOfCommitmentsRequest) ProtoMessage()    {}
func (*QueryNumberOfCommitmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{4}
}
func (m *QueryNumberOfCommitmentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNumberOfCommitmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNumberOfCommitmentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNumberOfCommitmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNumberOfCommitmentsRequest.Merge(m, src)
}
func (m *QueryNumberOfCommitmentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNumberOfCommitmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNumberOfCommitmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNumberOfCommitmentsRequest proto.InternalMessageInfo

type QueryNumberOfCommitmentsResponse struct {
	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (m *QueryNumberOfCommitmentsResponse) Reset()         { *m = QueryNumberOfCommitmentsResponse{} }
func (m *QueryNumberOfCommitmentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNumberOfCommitmentsResponse) ProtoMessage()    {}
func (*QueryNumberOfCommitmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{5}
}
func (m *QueryNumberOfCommitmentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNumberOfCommitmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNumberOfCommitmentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNumberOfCommitmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNumberOfCommitmentsResponse.Merge(m, src)
}
func (m *QueryNumberOfCommitmentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNumberOfCommitmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNumberOfCommitmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNumberOfCommitmentsResponse proto.InternalMessageInfo

func (m *QueryNumberOfCommitmentsResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type QueryCommittedTokensLockedRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryCommittedTokensLockedRequest) Reset()         { *m = QueryCommittedTokensLockedRequest{} }
func (m *QueryCommittedTokensLockedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCommittedTokensLockedRequest) ProtoMessage()    {}
func (*QueryCommittedTokensLockedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{6}
}
func (m *QueryCommittedTokensLockedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommittedTokensLockedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommittedTokensLockedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommittedTokensLockedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommittedTokensLockedRequest.Merge(m, src)
}
func (m *QueryCommittedTokensLockedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommittedTokensLockedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommittedTokensLockedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommittedTokensLockedRequest proto.InternalMessageInfo

func (m *QueryCommittedTokensLockedRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryCommittedTokensLockedResponse struct {
	Address         string                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	LockedCommitted github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=locked_committed,json=lockedCommitted,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"locked_committed"`
	TotalCommitted  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=total_committed,json=totalCommitted,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_committed"`
}

func (m *QueryCommittedTokensLockedResponse) Reset()         { *m = QueryCommittedTokensLockedResponse{} }
func (m *QueryCommittedTokensLockedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCommittedTokensLockedResponse) ProtoMessage()    {}
func (*QueryCommittedTokensLockedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{7}
}
func (m *QueryCommittedTokensLockedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommittedTokensLockedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommittedTokensLockedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommittedTokensLockedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommittedTokensLockedResponse.Merge(m, src)
}
func (m *QueryCommittedTokensLockedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommittedTokensLockedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommittedTokensLockedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommittedTokensLockedResponse proto.InternalMessageInfo

func (m *QueryCommittedTokensLockedResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryCommittedTokensLockedResponse) GetLockedCommitted() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.LockedCommitted
	}
	return nil
}

func (m *QueryCommittedTokensLockedResponse) GetTotalCommitted() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalCommitted
	}
	return nil
}

type QueryCommitmentVestingInfoRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryCommitmentVestingInfoRequest) Reset()         { *m = QueryCommitmentVestingInfoRequest{} }
func (m *QueryCommitmentVestingInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentVestingInfoRequest) ProtoMessage()    {}
func (*QueryCommitmentVestingInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{8}
}
func (m *QueryCommitmentVestingInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentVestingInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentVestingInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentVestingInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentVestingInfoRequest.Merge(m, src)
}
func (m *QueryCommitmentVestingInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentVestingInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentVestingInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentVestingInfoRequest proto.InternalMessageInfo

func (m *QueryCommitmentVestingInfoRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryCommitmentVestingInfoResponse struct {
	Total          cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total,proto3,customtype=cosmossdk.io/math.Int" json:"total"`
	VestingDetails []VestingDetails      `protobuf:"bytes,2,rep,name=vesting_details,json=vestingDetails,proto3" json:"vesting_details"`
}

func (m *QueryCommitmentVestingInfoResponse) Reset()         { *m = QueryCommitmentVestingInfoResponse{} }
func (m *QueryCommitmentVestingInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentVestingInfoResponse) ProtoMessage()    {}
func (*QueryCommitmentVestingInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{9}
}
func (m *QueryCommitmentVestingInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentVestingInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentVestingInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentVestingInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentVestingInfoResponse.Merge(m, src)
}
func (m *QueryCommitmentVestingInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentVestingInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentVestingInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentVestingInfoResponse proto.InternalMessageInfo

func (m *QueryCommitmentVestingInfoResponse) GetVestingDetails() []VestingDetails {
	if m != nil {
		return m.VestingDetails
	}
	return nil
}

type VestingDetails struct {
	Id              string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalVesting    cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_vesting,json=totalVesting,proto3,customtype=cosmossdk.io/math.Int" json:"total_vesting"`
	Claimed         cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=claimed,proto3,customtype=cosmossdk.io/math.Int" json:"claimed"`
	VestedSoFar     cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=vested_so_far,json=vestedSoFar,proto3,customtype=cosmossdk.io/math.Int" json:"vested_so_far"`
	RemainingBlocks int64                 `protobuf:"varint,5,opt,name=remaining_blocks,json=remainingBlocks,proto3" json:"remaining_blocks,omitempty"`
}

func (m *VestingDetails) Reset()         { *m = VestingDetails{} }
func (m *VestingDetails) String() string { return proto.CompactTextString(m) }
func (*VestingDetails) ProtoMessage()    {}
func (*VestingDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{10}
}
func (m *VestingDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingDetails.Merge(m, src)
}
func (m *VestingDetails) XXX_Size() int {
	return m.Size()
}
func (m *VestingDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VestingDetails proto.InternalMessageInfo

func (m *VestingDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VestingDetails) GetRemainingBlocks() int64 {
	if m != nil {
		return m.RemainingBlocks
	}
	return 0
}

type QueryAirDropRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAirDropRequest) Reset()         { *m = QueryAirDropRequest{} }
func (m *QueryAirDropRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAirDropRequest) ProtoMessage()    {}
func (*QueryAirDropRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{11}
}
func (m *QueryAirDropRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAirDropRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAirDropRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAirDropRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAirDropRequest.Merge(m, src)
}
func (m *QueryAirDropRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAirDropRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAirDropRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAirDropRequest proto.InternalMessageInfo

func (m *QueryAirDropRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAirDropResponse struct {
	AtomStaking cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=atom_staking,json=atomStaking,proto3,customtype=cosmossdk.io/math.Int" json:"atom_staking"`
	Cadet       cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=cadet,proto3,customtype=cosmossdk.io/math.Int" json:"cadet"`
	NftHolder   cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=nft_holder,json=nftHolder,proto3,customtype=cosmossdk.io/math.Int" json:"nft_holder"`
	Governor    cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=governor,proto3,customtype=cosmossdk.io/math.Int" json:"governor"`
	Claimed     bool                  `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`
}

func (m *QueryAirDropResponse) Reset()         { *m = QueryAirDropResponse{} }
func (m *QueryAirDropResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAirDropResponse) ProtoMessage()    {}
func (*QueryAirDropResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{12}
}
func (m *QueryAirDropResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAirDropResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAirDropResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAirDropResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAirDropResponse.Merge(m, src)
}
func (m *QueryAirDropResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAirDropResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAirDropResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAirDropResponse proto.InternalMessageInfo

func (m *QueryAirDropResponse) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

type QueryTotalAirDropClaimedRequest struct {
}

func (m *QueryTotalAirDropClaimedRequest) Reset()         { *m = QueryTotalAirDropClaimedRequest{} }
func (m *QueryTotalAirDropClaimedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalAirDropClaimedRequest) ProtoMessage()    {}
func (*QueryTotalAirDropClaimedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{13}
}
func (m *QueryTotalAirDropClaimedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalAirDropClaimedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalAirDropClaimedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalAirDropClaimedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalAirDropClaimedRequest.Merge(m, src)
}
func (m *QueryTotalAirDropClaimedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalAirDropClaimedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalAirDropClaimedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalAirDropClaimedRequest proto.InternalMessageInfo

type QueryTotalAirDropClaimedResponse struct {
	TotalElysClaimed cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_elys_claimed,json=totalElysClaimed,proto3,customtype=cosmossdk.io/math.Int" json:"total_elys_claimed"`
	TotalEdenClaimed cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_eden_claimed,json=totalEdenClaimed,proto3,customtype=cosmossdk.io/math.Int" json:"total_eden_claimed"`
}

func (m *QueryTotalAirDropClaimedResponse) Reset()         { *m = QueryTotalAirDropClaimedResponse{} }
func (m *QueryTotalAirDropClaimedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalAirDropClaimedResponse) ProtoMessage()    {}
func (*QueryTotalAirDropClaimedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3594c973c98f55d7, []int{14}
}
func (m *QueryTotalAirDropClaimedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalAirDropClaimedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalAirDropClaimedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalAirDropClaimedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalAirDropClaimedResponse.Merge(m, src)
}
func (m *QueryTotalAirDropClaimedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalAirDropClaimedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalAirDropClaimedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalAirDropClaimedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "elys.commitment.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "elys.commitment.QueryParamsResponse")
	proto.RegisterType((*QueryShowCommitmentsRequest)(nil), "elys.commitment.QueryShowCommitmentsRequest")
	proto.RegisterType((*QueryShowCommitmentsResponse)(nil), "elys.commitment.QueryShowCommitmentsResponse")
	proto.RegisterType((*QueryNumberOfCommitmentsRequest)(nil), "elys.commitment.QueryNumberOfCommitmentsRequest")
	proto.RegisterType((*QueryNumberOfCommitmentsResponse)(nil), "elys.commitment.QueryNumberOfCommitmentsResponse")
	proto.RegisterType((*QueryCommittedTokensLockedRequest)(nil), "elys.commitment.QueryCommittedTokensLockedRequest")
	proto.RegisterType((*QueryCommittedTokensLockedResponse)(nil), "elys.commitment.QueryCommittedTokensLockedResponse")
	proto.RegisterType((*QueryCommitmentVestingInfoRequest)(nil), "elys.commitment.QueryCommitmentVestingInfoRequest")
	proto.RegisterType((*QueryCommitmentVestingInfoResponse)(nil), "elys.commitment.QueryCommitmentVestingInfoResponse")
	proto.RegisterType((*VestingDetails)(nil), "elys.commitment.VestingDetails")
	proto.RegisterType((*QueryAirDropRequest)(nil), "elys.commitment.QueryAirDropRequest")
	proto.RegisterType((*QueryAirDropResponse)(nil), "elys.commitment.QueryAirDropResponse")
	proto.RegisterType((*QueryTotalAirDropClaimedRequest)(nil), "elys.commitment.QueryTotalAirDropClaimedRequest")
	proto.RegisterType((*QueryTotalAirDropClaimedResponse)(nil), "elys.commitment.QueryTotalAirDropClaimedResponse")
}

func init() { proto.RegisterFile("elys/commitment/query.proto", fileDescriptor_3594c973c98f55d7) }

var fileDescriptor_3594c973c98f55d7 = []byte{
	// 1136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x3a, 0x4d, 0xd2, 0x4c, 0xda, 0x38, 0x4c, 0x53, 0x70, 0xdd, 0xc8, 0x49, 0x96, 0x82,
	0x42, 0x69, 0xbc, 0x4d, 0xa2, 0x0a, 0x54, 0x0e, 0x10, 0xa7, 0xa5, 0x18, 0x55, 0xfd, 0xe3, 0x54,
	0x20, 0xb8, 0xac, 0xc6, 0xde, 0xb1, 0x3d, 0xb2, 0x77, 0xc6, 0xdd, 0x99, 0x38, 0x44, 0x55, 0x0f,
	0xf0, 0x05, 0x40, 0xe2, 0x4b, 0x20, 0x4e, 0x3d, 0x14, 0x71, 0xe1, 0x8c, 0xca, 0xad, 0x2a, 0x97,
	0x08, 0xa1, 0x82, 0x12, 0x24, 0xbe, 0x06, 0x9a, 0x3f, 0x6b, 0xaf, 0xed, 0xf5, 0xb6, 0x76, 0xb9,
	0x24, 0xbb, 0x3b, 0xef, 0xfd, 0xde, 0x6f, 0xde, 0xef, 0xcd, 0x7b, 0x63, 0x70, 0x1e, 0x37, 0x0f,
	0xb8, 0x53, 0x61, 0xbe, 0x4f, 0x84, 0x8f, 0xa9, 0x70, 0xee, 0xef, 0xe1, 0xe0, 0x20, 0xdf, 0x0a,
	0x98, 0x60, 0x30, 0x2d, 0x17, 0xf3, 0xdd, 0xc5, 0xec, 0x62, 0x8d, 0xd5, 0x98, 0x5a, 0x73, 0xe4,
	0x93, 0x36, 0xcb, 0x2e, 0xd5, 0x18, 0xab, 0x35, 0xb1, 0x83, 0x5a, 0xc4, 0x41, 0x94, 0x32, 0x81,
	0x04, 0x61, 0x94, 0x9b, 0xd5, 0x73, 0x15, 0xc6, 0x7d, 0xc6, 0x5d, 0xed, 0xa6, 0x5f, 0xcc, 0xd2,
	0x45, 0xfd, 0xe6, 0x94, 0x11, 0xc7, 0x3a, 0xb0, 0xd3, 0xde, 0x28, 0x63, 0x81, 0x36, 0x9c, 0x16,
	0xaa, 0x11, 0xaa, 0x70, 0xc2, 0x20, 0xfd, 0x44, 0x5b, 0x28, 0x40, 0x7e, 0x88, 0xb4, 0xda, 0xbf,
	0xda, 0x7d, 0x0c, 0x4d, 0x5e, 0x43, 0x3e, 0xa1, 0xcc, 0x51, 0x7f, 0xcd, 0xa7, 0x5c, 0x34, 0x7e,
	0x18, 0xb9, 0xc2, 0x88, 0x89, 0x69, 0x2f, 0x02, 0x78, 0x57, 0xb2, 0xba, 0xa3, 0x42, 0x95, 0xf0,
	0xfd, 0x3d, 0xcc, 0x85, 0x7d, 0x13, 0x9c, 0xe9, 0xf9, 0xca, 0x5b, 0x8c, 0x72, 0x0c, 0xaf, 0x80,
	0x69, 0x4d, 0x29, 0x63, 0xad, 0x58, 0x6b, 0x73, 0x9b, 0x6f, 0xe4, 0xfb, 0xb2, 0x97, 0xd7, 0x0e,
	0x85, 0x13, 0x4f, 0x9e, 0x2f, 0x4f, 0x94, 0x8c, 0xb1, 0x7d, 0x17, 0x9c, 0x57, 0x68, 0xbb, 0x75,
	0xb6, 0xbf, 0xd3, 0x25, 0x6d, 0x82, 0xc1, 0x4d, 0x30, 0x53, 0x09, 0x30, 0x12, 0x2c, 0x50, 0xb0,
	0xb3, 0x85, 0xcc, 0xb3, 0xc7, 0xeb, 0x8b, 0x26, 0x8b, 0xdb, 0x9e, 0x17, 0x60, 0xce, 0x77, 0x45,
	0x40, 0x68, 0xad, 0x14, 0x1a, 0xda, 0x04, 0x2c, 0xc5, 0x43, 0x1a, 0xa6, 0x45, 0x30, 0x17, 0x49,
	0x8f, 0xa1, 0xbb, 0x34, 0x40, 0x37, 0xe2, 0x5a, 0x98, 0x95, 0x9c, 0x7f, 0xf8, 0xf7, 0xd1, 0x45,
	0xab, 0x14, 0xf5, 0xb5, 0x57, 0xc1, 0xb2, 0x0a, 0x75, 0x6b, 0xcf, 0x2f, 0xe3, 0xe0, 0x76, 0x75,
	0x70, 0x07, 0xf6, 0x55, 0xb0, 0x32, 0xdc, 0xc4, 0x30, 0x7a, 0x1d, 0x4c, 0x53, 0xb5, 0xac, 0xc8,
	0x4c, 0x96, 0xcc, 0x9b, 0xfd, 0x39, 0x58, 0x55, 0xbe, 0xda, 0x47, 0x60, 0xef, 0x1e, 0x6b, 0x60,
	0xca, 0x6f, 0xb2, 0x4a, 0x03, 0x7b, 0x91, 0x14, 0x21, 0x9d, 0x88, 0x17, 0xa7, 0xc8, 0x18, 0xda,
	0xbf, 0xa6, 0x80, 0x9d, 0x84, 0x6c, 0x78, 0x8d, 0x01, 0x0d, 0xdb, 0x60, 0xa1, 0xa9, 0x50, 0xdc,
	0x4a, 0x88, 0x9d, 0x49, 0xad, 0x4c, 0xae, 0xcd, 0x6d, 0x9e, 0xcb, 0x1b, 0x4f, 0x59, 0x6f, 0x79,
	0x53, 0x6f, 0xf9, 0x1d, 0x46, 0x68, 0xe1, 0xb2, 0xcc, 0xef, 0x8f, 0x7f, 0x2d, 0xaf, 0xd5, 0x88,
	0xa8, 0xef, 0x95, 0xa5, 0x0c, 0xe6, 0xa8, 0x98, 0x7f, 0xeb, 0xdc, 0x6b, 0x38, 0xe2, 0xa0, 0x85,
	0xb9, 0x72, 0xe0, 0xa5, 0xb4, 0x0e, 0xd2, 0xe1, 0x0f, 0x05, 0x48, 0x0b, 0x26, 0x50, 0x33, 0x12,
	0x76, 0xf2, 0xff, 0x0f, 0x3b, 0xaf, 0x62, 0x74, 0xa2, 0xf6, 0x29, 0x24, 0x55, 0xfd, 0x0c, 0x73,
	0x41, 0x68, 0xad, 0x48, 0xab, 0xec, 0x55, 0x14, 0xfa, 0xc5, 0xea, 0x51, 0x68, 0x00, 0xd9, 0x28,
	0xb4, 0x0d, 0xa6, 0x14, 0x23, 0x03, 0xfc, 0xae, 0xdc, 0xd0, 0x1f, 0xcf, 0x97, 0xcf, 0x6a, 0x70,
	0xee, 0x35, 0xf2, 0x84, 0x39, 0x3e, 0x12, 0xf5, 0x7c, 0x91, 0x8a, 0x67, 0x8f, 0xd7, 0x81, 0x89,
	0x5a, 0xa4, 0xa2, 0xa4, 0x3d, 0xe1, 0x2e, 0x48, 0xb7, 0x35, 0xb2, 0xeb, 0x61, 0x81, 0x48, 0x93,
	0x1b, 0xbd, 0x96, 0x07, 0x8e, 0x84, 0x61, 0x70, 0x4d, 0x9b, 0x45, 0x4f, 0xc5, 0x7c, 0xbb, 0x67,
	0xc9, 0xfe, 0x29, 0x05, 0xe6, 0x7b, 0xad, 0xe1, 0x3c, 0x48, 0x11, 0x4f, 0xf3, 0x2c, 0xa5, 0x88,
	0x07, 0xef, 0x80, 0xd3, 0x5a, 0x30, 0xe3, 0x9a, 0x49, 0x8d, 0xbe, 0x85, 0x53, 0x0a, 0xc1, 0x04,
	0x82, 0xd7, 0xc1, 0x4c, 0xa5, 0x89, 0x88, 0xaf, 0xa4, 0x1f, 0x19, 0x2b, 0xf4, 0x85, 0xb7, 0xc1,
	0x69, 0x49, 0x09, 0x7b, 0x2e, 0x67, 0x6e, 0x15, 0x05, 0x99, 0x13, 0xa3, 0x83, 0xcd, 0x69, 0x84,
	0x5d, 0xf6, 0x31, 0x0a, 0xe0, 0x3b, 0x60, 0x21, 0xc0, 0x3e, 0x22, 0x54, 0xe6, 0xb8, 0x2c, 0x0b,
	0x97, 0x67, 0xa6, 0xd4, 0x41, 0x4f, 0x77, 0xbe, 0x17, 0xd4, 0x67, 0xbb, 0x68, 0x9a, 0xeb, 0x36,
	0x09, 0xae, 0x05, 0xac, 0xf5, 0x2a, 0x15, 0x74, 0x98, 0x02, 0x8b, 0xbd, 0x58, 0xa6, 0x66, 0x6e,
	0x81, 0x53, 0x48, 0x30, 0xdf, 0xe5, 0x02, 0x35, 0x64, 0xde, 0xc7, 0x28, 0x9d, 0x39, 0x09, 0xb0,
	0xab, 0xfd, 0x65, 0x0d, 0x56, 0x90, 0x87, 0xc5, 0x38, 0x02, 0x6a, 0x4f, 0xf8, 0x29, 0x00, 0xb4,
	0x2a, 0xdc, 0x3a, 0x6b, 0x7a, 0x38, 0x18, 0x47, 0xbc, 0x59, 0x5a, 0x15, 0x9f, 0x28, 0x6f, 0x78,
	0x03, 0x9c, 0xac, 0xb1, 0x36, 0x0e, 0x28, 0x1b, 0x4b, 0xb9, 0x8e, 0x33, 0xcc, 0x74, 0xcb, 0x49,
	0xaa, 0x75, 0xb2, 0x53, 0x21, 0x9d, 0xb6, 0x7f, 0x4f, 0x56, 0x9f, 0x49, 0xef, 0x8e, 0x5e, 0x0b,
	0xdb, 0xfe, 0xa1, 0x65, 0xfa, 0x7e, 0xac, 0x8d, 0x51, 0xe2, 0x0b, 0x00, 0xf5, 0x11, 0x90, 0x07,
	0xcd, 0x0d, 0x83, 0x8d, 0xa1, 0xc7, 0x82, 0x82, 0xb9, 0xde, 0x3c, 0xe0, 0x26, 0x44, 0x04, 0xda,
	0xc3, 0xb4, 0x03, 0x9d, 0x1a, 0x1b, 0xda, 0xc3, 0xd4, 0x40, 0x6f, 0xfe, 0x39, 0x0b, 0xa6, 0xd4,
	0xd6, 0xe0, 0xd7, 0x16, 0x98, 0xd6, 0x53, 0x1d, 0xbe, 0x39, 0xd0, 0x2c, 0x06, 0xaf, 0x0e, 0xd9,
	0x0b, 0xc9, 0x46, 0x3a, 0x2b, 0xf6, 0xa5, 0x6f, 0x7e, 0xff, 0xe7, 0xfb, 0xd4, 0xdb, 0xf0, 0x82,
	0x23, 0xad, 0xd7, 0x29, 0x16, 0xfb, 0x2c, 0x68, 0x38, 0xf1, 0x17, 0x20, 0xf8, 0xc8, 0x02, 0xe9,
	0xbe, 0x49, 0x0f, 0x2f, 0xc5, 0xc7, 0x89, 0xbf, 0x63, 0x64, 0xd7, 0x5f, 0xd2, 0xda, 0xd0, 0xfb,
	0x48, 0xd1, 0xbb, 0x0a, 0xdf, 0x4f, 0xa6, 0xc7, 0xeb, 0x6c, 0xdf, 0x8d, 0xdc, 0x15, 0x9c, 0x07,
	0xe6, 0x7e, 0xf2, 0x10, 0xfe, 0x66, 0x81, 0xb3, 0xb1, 0x83, 0x17, 0x6e, 0xc6, 0x53, 0x49, 0x9a,
	0xff, 0xd9, 0xad, 0x91, 0x7c, 0xcc, 0x26, 0x6e, 0xa8, 0x4d, 0x6c, 0xc3, 0x0f, 0x93, 0x37, 0xd1,
	0x99, 0xa5, 0xae, 0x50, 0x28, 0xae, 0x9e, 0xba, 0xce, 0x03, 0xd3, 0x64, 0x1e, 0xc2, 0x9f, 0x2d,
	0x70, 0x26, 0xe6, 0x6a, 0x03, 0x2f, 0xc7, 0xb3, 0x1a, 0x7e, 0x51, 0xca, 0x6e, 0x8c, 0xe0, 0x61,
	0x76, 0xf1, 0x81, 0xda, 0xc5, 0x15, 0xb8, 0x95, 0xbc, 0x0b, 0x7d, 0x9b, 0x72, 0x59, 0x35, 0xaa,
	0x47, 0x44, 0x85, 0xbe, 0xe1, 0x9a, 0xac, 0x42, 0xfc, 0x8c, 0x4f, 0x56, 0x61, 0xc8, 0xf4, 0x1e,
	0x4d, 0x05, 0xf9, 0x18, 0xce, 0x4a, 0x97, 0xd0, 0x2a, 0x8b, 0xa8, 0xf0, 0xad, 0x05, 0x66, 0x4c,
	0x8f, 0x81, 0x43, 0x0e, 0x59, 0xef, 0x44, 0xc9, 0xbe, 0xf5, 0x02, 0x2b, 0xc3, 0xf0, 0x3d, 0xc5,
	0x70, 0x03, 0x3a, 0xc9, 0x0c, 0x11, 0x09, 0xbc, 0x80, 0xb5, 0xfa, 0xea, 0x22, 0x6c, 0x7d, 0x5e,
	0xb7, 0xf5, 0x0d, 0xab, 0x8b, 0xe1, 0x9d, 0x74, 0x58, 0x5d, 0x24, 0xf4, 0xd5, 0x97, 0xad, 0x0b,
	0xdd, 0x20, 0x0d, 0xf7, 0xb0, 0x47, 0x16, 0x8a, 0x4f, 0x8e, 0x72, 0xd6, 0xd3, 0xa3, 0x9c, 0xf5,
	0xf7, 0x51, 0xce, 0xfa, 0xee, 0x38, 0x37, 0xf1, 0xf4, 0x38, 0x37, 0x71, 0x78, 0x9c, 0x9b, 0xf8,
	0xd2, 0x89, 0x5c, 0x13, 0x07, 0x81, 0xbf, 0xea, 0x81, 0x96, 0x77, 0xc6, 0xf2, 0xb4, 0xfa, 0x1d,
	0xb5, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x38, 0x75, 0xcb, 0x66, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Commitment item.
	ShowCommitments(ctx context.Context, in *QueryShowCommitmentsRequest, opts ...grpc.CallOption) (*QueryShowCommitmentsResponse, error)
	// Queries sum of committed tokens locked and not unlockable
	CommittedTokensLocked(ctx context.Context, in *QueryCommittedTokensLockedRequest, opts ...grpc.CallOption) (*QueryCommittedTokensLockedResponse, error)
	// Queries the total number of commitment items.
	NumberOfCommitments(ctx context.Context, in *QueryNumberOfCommitmentsRequest, opts ...grpc.CallOption) (*QueryNumberOfCommitmentsResponse, error)
	// Queries a list of CommitmentVestingInfo items.
	CommitmentVestingInfo(ctx context.Context, in *QueryCommitmentVestingInfoRequest, opts ...grpc.CallOption) (*QueryCommitmentVestingInfoResponse, error)
	AirDrop(ctx context.Context, in *QueryAirDropRequest, opts ...grpc.CallOption) (*QueryAirDropResponse, error)
	TotalAirdropClaimed(ctx context.Context, in *QueryTotalAirDropClaimedRequest, opts ...grpc.CallOption) (*QueryTotalAirDropClaimedResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowCommitments(ctx context.Context, in *QueryShowCommitmentsRequest, opts ...grpc.CallOption) (*QueryShowCommitmentsResponse, error) {
	out := new(QueryShowCommitmentsResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/ShowCommitments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CommittedTokensLocked(ctx context.Context, in *QueryCommittedTokensLockedRequest, opts ...grpc.CallOption) (*QueryCommittedTokensLockedResponse, error) {
	out := new(QueryCommittedTokensLockedResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/CommittedTokensLocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NumberOfCommitments(ctx context.Context, in *QueryNumberOfCommitmentsRequest, opts ...grpc.CallOption) (*QueryNumberOfCommitmentsResponse, error) {
	out := new(QueryNumberOfCommitmentsResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/NumberOfCommitments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CommitmentVestingInfo(ctx context.Context, in *QueryCommitmentVestingInfoRequest, opts ...grpc.CallOption) (*QueryCommitmentVestingInfoResponse, error) {
	out := new(QueryCommitmentVestingInfoResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/CommitmentVestingInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AirDrop(ctx context.Context, in *QueryAirDropRequest, opts ...grpc.CallOption) (*QueryAirDropResponse, error) {
	out := new(QueryAirDropResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/AirDrop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalAirdropClaimed(ctx context.Context, in *QueryTotalAirDropClaimedRequest, opts ...grpc.CallOption) (*QueryTotalAirDropClaimedResponse, error) {
	out := new(QueryTotalAirDropClaimedResponse)
	err := c.cc.Invoke(ctx, "/elys.commitment.Query/TotalAirdropClaimed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Commitment item.
	ShowCommitments(context.Context, *QueryShowCommitmentsRequest) (*QueryShowCommitmentsResponse, error)
	// Queries sum of committed tokens locked and not unlockable
	CommittedTokensLocked(context.Context, *QueryCommittedTokensLockedRequest) (*QueryCommittedTokensLockedResponse, error)
	// Queries the total number of commitment items.
	NumberOfCommitments(context.Context, *QueryNumberOfCommitmentsRequest) (*QueryNumberOfCommitmentsResponse, error)
	// Queries a list of CommitmentVestingInfo items.
	CommitmentVestingInfo(context.Context, *QueryCommitmentVestingInfoRequest) (*QueryCommitmentVestingInfoResponse, error)
	AirDrop(context.Context, *QueryAirDropRequest) (*QueryAirDropResponse, error)
	TotalAirdropClaimed(context.Context, *QueryTotalAirDropClaimedRequest) (*QueryTotalAirDropClaimedResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ShowCommitments(ctx context.Context, req *QueryShowCommitmentsRequest) (*QueryShowCommitmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowCommitments not implemented")
}
func (*UnimplementedQueryServer) CommittedTokensLocked(ctx context.Context, req *QueryCommittedTokensLockedRequest) (*QueryCommittedTokensLockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommittedTokensLocked not implemented")
}
func (*UnimplementedQueryServer) NumberOfCommitments(ctx context.Context, req *QueryNumberOfCommitmentsRequest) (*QueryNumberOfCommitmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NumberOfCommitments not implemented")
}
func (*UnimplementedQueryServer) CommitmentVestingInfo(ctx context.Context, req *QueryCommitmentVestingInfoRequest) (*QueryCommitmentVestingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitmentVestingInfo not implemented")
}
func (*UnimplementedQueryServer) AirDrop(ctx context.Context, req *QueryAirDropRequest) (*QueryAirDropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirDrop not implemented")
}
func (*UnimplementedQueryServer) TotalAirdropClaimed(ctx context.Context, req *QueryTotalAirDropClaimedRequest) (*QueryTotalAirDropClaimedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalAirdropClaimed not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowCommitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowCommitmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowCommitments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/ShowCommitments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowCommitments(ctx, req.(*QueryShowCommitmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CommittedTokensLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommittedTokensLockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommittedTokensLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/CommittedTokensLocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommittedTokensLocked(ctx, req.(*QueryCommittedTokensLockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NumberOfCommitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNumberOfCommitmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NumberOfCommitments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/NumberOfCommitments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NumberOfCommitments(ctx, req.(*QueryNumberOfCommitmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CommitmentVestingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentVestingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitmentVestingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/CommitmentVestingInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitmentVestingInfo(ctx, req.(*QueryCommitmentVestingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AirDrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAirDropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AirDrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/AirDrop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AirDrop(ctx, req.(*QueryAirDropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalAirdropClaimed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalAirDropClaimedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalAirdropClaimed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elys.commitment.Query/TotalAirdropClaimed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalAirdropClaimed(ctx, req.(*QueryTotalAirDropClaimedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "elys.commitment.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowCommitments",
			Handler:    _Query_ShowCommitments_Handler,
		},
		{
			MethodName: "CommittedTokensLocked",
			Handler:    _Query_CommittedTokensLocked_Handler,
		},
		{
			MethodName: "NumberOfCommitments",
			Handler:    _Query_NumberOfCommitments_Handler,
		},
		{
			MethodName: "CommitmentVestingInfo",
			Handler:    _Query_CommitmentVestingInfo_Handler,
		},
		{
			MethodName: "AirDrop",
			Handler:    _Query_AirDrop_Handler,
		},
		{
			MethodName: "TotalAirdropClaimed",
			Handler:    _Query_TotalAirdropClaimed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "elys/commitment/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryShowCommitmentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowCommitmentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowCommitmentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowCommitmentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowCommitmentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowCommitmentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Commitments.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryNumberOfCommitmentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNumberOfCommitmentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNumberOfCommitmentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryNumberOfCommitmentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNumberOfCommitmentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNumberOfCommitmentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Number != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommittedTokensLockedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommittedTokensLockedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommittedTokensLockedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommittedTokensLockedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommittedTokensLockedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommittedTokensLockedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalCommitted) > 0 {
		for iNdEx := len(m.TotalCommitted) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalCommitted[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.LockedCommitted) > 0 {
		for iNdEx := len(m.LockedCommitted) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LockedCommitted[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommitmentVestingInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentVestingInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentVestingInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommitmentVestingInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentVestingInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentVestingInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VestingDetails) > 0 {
		for iNdEx := len(m.VestingDetails) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingDetails[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size := m.Total.Size()
		i -= size
		if _, err := m.Total.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VestingDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemainingBlocks != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RemainingBlocks))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.VestedSoFar.Size()
		i -= size
		if _, err := m.VestedSoFar.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Claimed.Size()
		i -= size
		if _, err := m.Claimed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalVesting.Size()
		i -= size
		if _, err := m.TotalVesting.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAirDropRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAirDropRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAirDropRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAirDropResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAirDropResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAirDropResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Claimed {
		i--
		if m.Claimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Governor.Size()
		i -= size
		if _, err := m.Governor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.NftHolder.Size()
		i -= size
		if _, err := m.NftHolder.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Cadet.Size()
		i -= size
		if _, err := m.Cadet.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.AtomStaking.Size()
		i -= size
		if _, err := m.AtomStaking.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTotalAirDropClaimedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalAirDropClaimedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalAirDropClaimedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTotalAirDropClaimedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalAirDropClaimedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalAirDropClaimedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalEdenClaimed.Size()
		i -= size
		if _, err := m.TotalEdenClaimed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalElysClaimed.Size()
		i -= size
		if _, err := m.TotalElysClaimed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryShowCommitmentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowCommitmentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Commitments.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryNumberOfCommitmentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryNumberOfCommitmentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovQuery(uint64(m.Number))
	}
	return n
}

func (m *QueryCommittedTokensLockedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCommittedTokensLockedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.LockedCommitted) > 0 {
		for _, e := range m.LockedCommitted {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TotalCommitted) > 0 {
		for _, e := range m.TotalCommitted {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryCommitmentVestingInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCommitmentVestingInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Total.Size()
	n += 1 + l + sovQuery(uint64(l))
	if len(m.VestingDetails) > 0 {
		for _, e := range m.VestingDetails {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *VestingDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.TotalVesting.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Claimed.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.VestedSoFar.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.RemainingBlocks != 0 {
		n += 1 + sovQuery(uint64(m.RemainingBlocks))
	}
	return n
}

func (m *QueryAirDropRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAirDropResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AtomStaking.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Cadet.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.NftHolder.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Governor.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.Claimed {
		n += 2
	}
	return n
}

func (m *QueryTotalAirDropClaimedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTotalAirDropClaimedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalElysClaimed.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.TotalEdenClaimed.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowCommitmentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowCommitmentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowCommitmentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowCommitmentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowCommitmentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowCommitmentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commitments.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNumberOfCommitmentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNumberOfCommitmentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNumberOfCommitmentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNumberOfCommitmentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNumberOfCommitmentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNumberOfCommitmentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommittedTokensLockedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommittedTokensLockedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommittedTokensLockedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommittedTokensLockedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommittedTokensLockedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommittedTokensLockedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedCommitted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockedCommitted = append(m.LockedCommitted, types.Coin{})
			if err := m.LockedCommitted[len(m.LockedCommitted)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCommitted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalCommitted = append(m.TotalCommitted, types.Coin{})
			if err := m.TotalCommitted[len(m.TotalCommitted)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommitmentVestingInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentVestingInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentVestingInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommitmentVestingInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentVestingInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentVestingInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingDetails = append(m.VestingDetails, VestingDetails{})
			if err := m.VestingDetails[len(m.VestingDetails)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVesting", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalVesting.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Claimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestedSoFar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VestedSoFar.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBlocks", wireType)
			}
			m.RemainingBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAirDropRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAirDropRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAirDropRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAirDropResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAirDropResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAirDropResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtomStaking", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AtomStaking.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cadet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cadet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftHolder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NftHolder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Governor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Governor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalAirDropClaimedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalAirDropClaimedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalAirDropClaimedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalAirDropClaimedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalAirDropClaimedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalAirDropClaimedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalElysClaimed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalElysClaimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEdenClaimed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalEdenClaimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
