version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: elys_indexer_postgres
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: elys_indexer
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer -d elys_indexer"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: elys_indexer_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: ..
      dockerfile: indexer/Dockerfile
    container_name: elys_indexer
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
    ports:
      - "8080:8080"  # WebSocket server
      - "9090:9090"  # Metrics
    restart: unless-stopped
    command: ["/app/elys-indexer", "-c", "/app/config.yaml"]

volumes:
  postgres_data:
  redis_data: