# CLOB Matching Bot Configuration

bot:
  # Unique identifier for this bot instance
  engine_id: "matching-bot-1"
  
  # Mnemonic for the bot's wallet (KEEP THIS SECRET!)
  # Example mnemonic - REPLACE WITH YOUR OWN
  mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
  
  # Account number and sequence (will be fetched automatically if not set)
  account_number: 0
  account_sequence: 0
  
  # How often to check for matching opportunities
  matching_interval: 500ms
  
  # Maximum number of matches to include in a single transaction
  max_batch_size: 10
  
  # Minimum profit required in basis points (100 bps = 1%)
  min_profit_bps: 10

chain:
  # Chain configuration
  chain_id: "elys-1"
  rpc_endpoint: "http://localhost:26657"
  grpc_endpoint: "localhost:9090"
  
  # Gas configuration
  gas_price: "0.01uelys"
  gas_limit: 500000
  
  # Native denomination
  denom: "uelys"

indexer:
  # Indexer API endpoint
  url: "http://localhost:8080"

# List of market IDs to monitor
markets:
  - 1  # BTC/USDC
  - 2  # ETH/USDC
  - 3  # ATOM/USDC