# CLOB Matching Bot Configuration (Secure Version)
# Uses environment variables for sensitive data

bot:
  # Unique identifier for this bot instance
  engine_id: ${BOT_ENGINE_ID:-matching-bot-1}
  
  # Mnemonic for the bot's wallet - MUST be set via environment variable
  mnemonic: ${BOT_MNEMONIC}
  
  # Account number and sequence (will be fetched automatically if not set)
  account_number: ${BOT_ACCOUNT_NUMBER:-0}
  account_sequence: ${BOT_ACCOUNT_SEQUENCE:-0}
  
  # How often to check for matching opportunities
  matching_interval: ${BOT_MATCHING_INTERVAL:-500ms}
  
  # Maximum number of matches to include in a single transaction
  max_batch_size: ${BOT_MAX_BATCH_SIZE:-10}
  
  # Minimum profit required in basis points (100 bps = 1%)
  min_profit_bps: ${BOT_MIN_PROFIT_BPS:-10}

chain:
  # Chain configuration
  chain_id: ${CHAIN_ID:-elys-1}
  rpc_endpoint: ${CHAIN_RPC_ENDPOINT:-http://localhost:26657}
  grpc_endpoint: ${CHAIN_GRPC_ENDPOINT:-localhost:9090}
  
  # Gas configuration
  gas_price: ${CHAIN_GAS_PRICE:-0.01uelys}
  gas_limit: ${CHAIN_GAS_LIMIT:-500000}
  
  # Native denomination
  denom: ${CHAIN_DENOM:-uelys}

indexer:
  # Indexer API endpoint
  url: ${INDEXER_URL:-http://localhost:8080}

# List of market IDs to monitor
# Can be overridden with MARKETS environment variable (comma-separated)
markets: ${MARKETS:-[1,2,3]}