# Builder
FROM golang:1.19-alpine AS builder

RUN apk add --no-cache \
    ca-certificates \
    build-base \
    linux-headers \
    git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY price-feeder .
RUN LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true make build

# Runner
FROM alpine
RUN apk add bash

WORKDIR /app

COPY --from=builder /app/build/price-feeder /bin/price-feeder

EXPOSE 7171

ENTRYPOINT ["price-feeder", "/root/.feeder/price-feeder.toml"]
