// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: elys/clob/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the clob module's genesis state.
type GenesisState struct {
	Params           Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	SubAccounts      []SubAccount      `protobuf:"bytes,2,rep,name=sub_accounts,json=subAccounts,proto3" json:"sub_accounts"`
	PerpetualMarkets []PerpetualMarket `protobuf:"bytes,3,rep,name=perpetual_markets,json=perpetualMarkets,proto3" json:"perpetual_markets"`
	Perpetuals       []Perpetual       `protobuf:"bytes,4,rep,name=perpetuals,proto3" json:"perpetuals"`
	PerpetualOwners  []PerpetualOwner  `protobuf:"bytes,5,rep,name=perpetual_owners,json=perpetualOwners,proto3" json:"perpetual_owners"`
	// Based on market id, it will have order book for all assets
	OrderBooks        []*PerpetualOrder   `protobuf:"bytes,6,rep,name=order_books,json=orderBooks,proto3" json:"order_books,omitempty"`
	TwapPrices        []*TwapPrice        `protobuf:"bytes,7,rep,name=twap_prices,json=twapPrices,proto3" json:"twap_prices,omitempty"`
	PerpetualCounters []*PerpetualCounter `protobuf:"bytes,8,rep,name=perpetual_counters,json=perpetualCounters,proto3" json:"perpetual_counters,omitempty"`
	FundingRates      []*FundingRate      `protobuf:"bytes,9,rep,name=funding_rates,json=fundingRates,proto3" json:"funding_rates,omitempty"`
	PerpetualADLs     []*PerpetualADL     `protobuf:"bytes,10,rep,name=perpetualADLs,proto3" json:"perpetualADLs,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee42208eb1f705a1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSubAccounts() []SubAccount {
	if m != nil {
		return m.SubAccounts
	}
	return nil
}

func (m *GenesisState) GetPerpetualMarkets() []PerpetualMarket {
	if m != nil {
		return m.PerpetualMarkets
	}
	return nil
}

func (m *GenesisState) GetPerpetuals() []Perpetual {
	if m != nil {
		return m.Perpetuals
	}
	return nil
}

func (m *GenesisState) GetPerpetualOwners() []PerpetualOwner {
	if m != nil {
		return m.PerpetualOwners
	}
	return nil
}

func (m *GenesisState) GetOrderBooks() []*PerpetualOrder {
	if m != nil {
		return m.OrderBooks
	}
	return nil
}

func (m *GenesisState) GetTwapPrices() []*TwapPrice {
	if m != nil {
		return m.TwapPrices
	}
	return nil
}

func (m *GenesisState) GetPerpetualCounters() []*PerpetualCounter {
	if m != nil {
		return m.PerpetualCounters
	}
	return nil
}

func (m *GenesisState) GetFundingRates() []*FundingRate {
	if m != nil {
		return m.FundingRates
	}
	return nil
}

func (m *GenesisState) GetPerpetualADLs() []*PerpetualADL {
	if m != nil {
		return m.PerpetualADLs
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "elys.clob.GenesisState")
}

func init() { proto.RegisterFile("elys/clob/genesis.proto", fileDescriptor_ee42208eb1f705a1) }

var fileDescriptor_ee42208eb1f705a1 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0xb6, 0x15, 0xe6, 0x74, 0x82, 0x99, 0xfd, 0xf1, 0x8a, 0x14, 0x26, 0x4e, 0xe3,
	0x40, 0x22, 0x0d, 0x71, 0x01, 0x81, 0xd4, 0x6e, 0x02, 0x09, 0x6d, 0x62, 0xca, 0x38, 0x71, 0x89,
	0x9c, 0xd4, 0x0b, 0x55, 0xdb, 0xd8, 0xf2, 0xeb, 0xa8, 0xec, 0x5b, 0xc0, 0xb7, 0xda, 0x71, 0x47,
	0x4e, 0x08, 0xb5, 0x5f, 0x04, 0xd9, 0x71, 0xe3, 0x54, 0xad, 0xb8, 0xc5, 0xcf, 0xf3, 0xbc, 0xbf,
	0xf7, 0x7d, 0x63, 0xa3, 0x43, 0x36, 0xbe, 0x85, 0x28, 0x1b, 0xf3, 0x34, 0xca, 0x59, 0xc1, 0x60,
	0x08, 0xa1, 0x90, 0x5c, 0x71, 0xbc, 0xad, 0x8d, 0x50, 0x1b, 0xdd, 0xbd, 0x9c, 0xe7, 0xdc, 0xa8,
	0x91, 0xfe, 0xaa, 0x02, 0xdd, 0x03, 0x57, 0x29, 0xa8, 0xa4, 0x13, 0x58, 0xd5, 0x27, 0x54, 0x8e,
	0x98, 0xb2, 0xfa, 0xbe, 0xd3, 0xb9, 0x1c, 0x30, 0x69, 0xe5, 0xa3, 0x06, 0x86, 0x49, 0xc1, 0x54,
	0x49, 0xc7, 0xd6, 0xea, 0x3a, 0x0b, 0xca, 0x94, 0x66, 0x19, 0x2f, 0x8b, 0x05, 0xed, 0xa9, 0xf3,
	0xe8, 0xc0, 0x16, 0xbc, 0xf8, 0xb5, 0x85, 0x3a, 0x9f, 0xaa, 0x2d, 0xae, 0x15, 0x55, 0x0c, 0x47,
	0xa8, 0x5d, 0xcd, 0x46, 0xbc, 0x63, 0xef, 0xc4, 0x3f, 0xdd, 0x0d, 0xeb, 0xad, 0xc2, 0x2b, 0x63,
	0xf4, 0x37, 0xef, 0xfe, 0x3c, 0x6f, 0xc5, 0x36, 0x86, 0x3f, 0xa0, 0x0e, 0x94, 0x69, 0x62, 0x7b,
	0x01, 0x79, 0x70, 0xbc, 0x71, 0xe2, 0x9f, 0xee, 0x37, 0xca, 0xae, 0xcb, 0xb4, 0x57, 0xb9, 0xb6,
	0xd4, 0x87, 0x5a, 0x01, 0x7c, 0x89, 0x76, 0xeb, 0x2d, 0x92, 0x6a, 0x7d, 0x20, 0x1b, 0x06, 0xd2,
	0x6d, 0xf6, 0x5e, 0x64, 0x2e, 0x4d, 0xc4, 0x92, 0x9e, 0x88, 0x65, 0x19, 0xf0, 0x5b, 0x84, 0x6a,
	0x0d, 0xc8, 0xa6, 0xe1, 0xec, 0xad, 0xe3, 0x58, 0x42, 0x23, 0x8d, 0x3f, 0x23, 0xc7, 0x4b, 0xf8,
	0xb4, 0x60, 0x12, 0xc8, 0x96, 0x21, 0x1c, 0xad, 0x23, 0x7c, 0xd1, 0x09, 0x8b, 0x79, 0x2c, 0x96,
	0x54, 0x3d, 0x87, 0x6f, 0xee, 0x2c, 0x49, 0x39, 0x1f, 0x01, 0x69, 0xff, 0x07, 0xa3, 0x63, 0x31,
	0x32, 0xe9, 0xbe, 0x0e, 0xe3, 0x37, 0xc8, 0x57, 0x53, 0x2a, 0x12, 0x21, 0x87, 0x19, 0x03, 0xf2,
	0x70, 0x65, 0x89, 0xaf, 0x53, 0x2a, 0xae, 0xb4, 0x19, 0x23, 0xb5, 0xf8, 0xd4, 0xe3, 0x63, 0x37,
	0xbe, 0xf9, 0xbb, 0x7a, 0x81, 0x47, 0xa6, 0xfa, 0xd9, 0xba, 0xce, 0x67, 0x55, 0x26, 0x76, 0x17,
	0x60, 0x15, 0xc0, 0xef, 0xd0, 0xce, 0x4d, 0x59, 0x0c, 0x86, 0x45, 0x9e, 0x48, 0xaa, 0x18, 0x90,
	0x6d, 0x83, 0x39, 0x68, 0x60, 0x3e, 0x56, 0x7e, 0x4c, 0x15, 0x8b, 0x3b, 0x37, 0xee, 0x00, 0xf8,
	0x3d, 0xda, 0xa9, 0x89, 0xbd, 0xf3, 0x0b, 0x20, 0xc8, 0x14, 0x1f, 0xae, 0x9b, 0xa1, 0x77, 0x7e,
	0x11, 0x2f, 0xa7, 0xfb, 0x67, 0x77, 0xb3, 0xc0, 0xbb, 0x9f, 0x05, 0xde, 0xdf, 0x59, 0xe0, 0xfd,
	0x9c, 0x07, 0xad, 0xfb, 0x79, 0xd0, 0xfa, 0x3d, 0x0f, 0x5a, 0xdf, 0x5e, 0xe6, 0x43, 0xf5, 0xbd,
	0x4c, 0xc3, 0x8c, 0x4f, 0x22, 0xcd, 0x7a, 0x55, 0x30, 0x35, 0xe5, 0x72, 0x64, 0x0e, 0xd1, 0x8f,
	0xea, 0x71, 0xab, 0x5b, 0xc1, 0x20, 0x6d, 0x9b, 0xf7, 0xfd, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe9, 0x60, 0x23, 0x70, 0xae, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PerpetualADLs) > 0 {
		for iNdEx := len(m.PerpetualADLs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerpetualADLs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.FundingRates) > 0 {
		for iNdEx := len(m.FundingRates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FundingRates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.PerpetualCounters) > 0 {
		for iNdEx := len(m.PerpetualCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerpetualCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.TwapPrices) > 0 {
		for iNdEx := len(m.TwapPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TwapPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.OrderBooks) > 0 {
		for iNdEx := len(m.OrderBooks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderBooks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PerpetualOwners) > 0 {
		for iNdEx := len(m.PerpetualOwners) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerpetualOwners[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Perpetuals) > 0 {
		for iNdEx := len(m.Perpetuals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Perpetuals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PerpetualMarkets) > 0 {
		for iNdEx := len(m.PerpetualMarkets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerpetualMarkets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SubAccounts) > 0 {
		for iNdEx := len(m.SubAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.SubAccounts) > 0 {
		for _, e := range m.SubAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PerpetualMarkets) > 0 {
		for _, e := range m.PerpetualMarkets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Perpetuals) > 0 {
		for _, e := range m.Perpetuals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PerpetualOwners) > 0 {
		for _, e := range m.PerpetualOwners {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OrderBooks) > 0 {
		for _, e := range m.OrderBooks {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TwapPrices) > 0 {
		for _, e := range m.TwapPrices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PerpetualCounters) > 0 {
		for _, e := range m.PerpetualCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FundingRates) > 0 {
		for _, e := range m.FundingRates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PerpetualADLs) > 0 {
		for _, e := range m.PerpetualADLs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubAccounts = append(m.SubAccounts, SubAccount{})
			if err := m.SubAccounts[len(m.SubAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpetualMarkets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerpetualMarkets = append(m.PerpetualMarkets, PerpetualMarket{})
			if err := m.PerpetualMarkets[len(m.PerpetualMarkets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Perpetuals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Perpetuals = append(m.Perpetuals, Perpetual{})
			if err := m.Perpetuals[len(m.Perpetuals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpetualOwners", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerpetualOwners = append(m.PerpetualOwners, PerpetualOwner{})
			if err := m.PerpetualOwners[len(m.PerpetualOwners)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderBooks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderBooks = append(m.OrderBooks, &PerpetualOrder{})
			if err := m.OrderBooks[len(m.OrderBooks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwapPrices = append(m.TwapPrices, &TwapPrice{})
			if err := m.TwapPrices[len(m.TwapPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpetualCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerpetualCounters = append(m.PerpetualCounters, &PerpetualCounter{})
			if err := m.PerpetualCounters[len(m.PerpetualCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingRates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundingRates = append(m.FundingRates, &FundingRate{})
			if err := m.FundingRates[len(m.FundingRates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpetualADLs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerpetualADLs = append(m.PerpetualADLs, &PerpetualADL{})
			if err := m.PerpetualADLs[len(m.PerpetualADLs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
