// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: elys/clob/subaccount.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubAccount struct {
	Owner       string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id          uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TradeNounce uint64 `protobuf:"varint,3,opt,name=trade_nounce,json=tradeNounce,proto3" json:"trade_nounce,omitempty"`
}

func (m *SubAccount) Reset()         { *m = SubAccount{} }
func (m *SubAccount) String() string { return proto.CompactTextString(m) }
func (*SubAccount) ProtoMessage()    {}
func (*SubAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_796473dabe88ec78, []int{0}
}
func (m *SubAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubAccount.Merge(m, src)
}
func (m *SubAccount) XXX_Size() int {
	return m.Size()
}
func (m *SubAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SubAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SubAccount proto.InternalMessageInfo

func (m *SubAccount) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SubAccount) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubAccount) GetTradeNounce() uint64 {
	if m != nil {
		return m.TradeNounce
	}
	return 0
}

func init() {
	proto.RegisterType((*SubAccount)(nil), "elys.clob.SubAccount")
}

func init() { proto.RegisterFile("elys/clob/subaccount.proto", fileDescriptor_796473dabe88ec78) }

var fileDescriptor_796473dabe88ec78 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x90, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xe3, 0x70, 0x91, 0x6a, 0x10, 0x43, 0xd4, 0x21, 0x64, 0xb0, 0x0a, 0x53, 0x07, 0x1a,
	0xab, 0x42, 0x62, 0x6f, 0x07, 0x46, 0x86, 0x76, 0x63, 0xa9, 0x62, 0xe7, 0x28, 0x58, 0xb4, 0x3e,
	0x95, 0x2f, 0x2d, 0x7d, 0x0b, 0x1e, 0x86, 0x87, 0x60, 0xac, 0x98, 0x18, 0x51, 0xf2, 0x22, 0x28,
	0x76, 0xb7, 0xf3, 0xff, 0xdf, 0xaf, 0x73, 0xa3, 0x05, 0xac, 0x0f, 0x96, 0xcb, 0x35, 0x0a, 0x6e,
	0xbd, 0xa8, 0xa4, 0x44, 0xaf, 0x5d, 0xb9, 0x35, 0xe8, 0x30, 0x1b, 0xf4, 0xac, 0xec, 0x59, 0x31,
	0x6c, 0xb0, 0xc1, 0xe0, 0xf2, 0xbe, 0x8a, 0x81, 0xe2, 0x56, 0xa2, 0xdd, 0xa0, 0x5d, 0x45, 0x10,
	0xc5, 0x09, 0xb1, 0xa8, 0xb8, 0xa8, 0x2c, 0xf0, 0xdd, 0x54, 0x80, 0xab, 0xa6, 0x5c, 0xa2, 0xd2,
	0x91, 0xdf, 0x23, 0xa5, 0x4b, 0x2f, 0x66, 0x71, 0x5e, 0x56, 0xd2, 0x0b, 0xdc, 0x6b, 0x30, 0x39,
	0x19, 0x91, 0xf1, 0x60, 0x9e, 0xff, 0x7c, 0x4d, 0x86, 0xa7, 0x76, 0xb3, 0xba, 0x36, 0x60, 0xed,
	0xd2, 0x19, 0xa5, 0x9b, 0x45, 0x8c, 0x65, 0x37, 0x34, 0x55, 0x75, 0x9e, 0x8e, 0xc8, 0xf8, 0x7c,
	0x91, 0xaa, 0x3a, 0xbb, 0xa3, 0xd7, 0xce, 0x54, 0x35, 0xac, 0x34, 0x7a, 0x2d, 0x21, 0x3f, 0x0b,
	0xe4, 0x2a, 0x78, 0x2f, 0xc1, 0x9a, 0x3f, 0x7f, 0xb7, 0x8c, 0x1c, 0x5b, 0x46, 0xfe, 0x5a, 0x46,
	0x3e, 0x3b, 0x96, 0x1c, 0x3b, 0x96, 0xfc, 0x76, 0x2c, 0x79, 0x7d, 0x68, 0x94, 0x7b, 0xf3, 0xa2,
	0x94, 0xb8, 0xe1, 0xfd, 0xc5, 0x13, 0x0d, 0x6e, 0x8f, 0xe6, 0x3d, 0x08, 0xbe, 0x7b, 0xe2, 0x1f,
	0xf1, 0x3f, 0xee, 0xb0, 0x05, 0x2b, 0x2e, 0xc3, 0xfe, 0x8f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x5b, 0xfa, 0x63, 0x3d, 0x39, 0x01, 0x00, 0x00,
}

func (m *SubAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TradeNounce != 0 {
		i = encodeVarintSubaccount(dAtA, i, uint64(m.TradeNounce))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintSubaccount(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintSubaccount(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSubaccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovSubaccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovSubaccount(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovSubaccount(uint64(m.Id))
	}
	if m.TradeNounce != 0 {
		n += 1 + sovSubaccount(uint64(m.TradeNounce))
	}
	return n
}

func sovSubaccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSubaccount(x uint64) (n int) {
	return sovSubaccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubaccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubaccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubaccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubaccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubaccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeNounce", wireType)
			}
			m.TradeNounce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubaccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TradeNounce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubaccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubaccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSubaccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSubaccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubaccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubaccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSubaccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSubaccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSubaccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSubaccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSubaccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSubaccount = fmt.Errorf("proto: unexpected end of group")
)
