name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_tag }}

      - name: Clean Go build cache
        run: |
          go clean -cache -modcache -testcache || true
          rm -rf /root/.cache/go-build /tmp/* || true
          sudo apt-get clean || true

      - name: Make release
        run: |
          sudo rm -rf dist
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
