name: Create release

on:
  push:
    tags:
      - v*
  # Add this manual trigger
  workflow_dispatch:
    # Add an input field for the tag or branch name
    inputs:
      git-ref:
        description: 'The git ref (tag, branch, or commit SHA) to run on'
        required: true
        default: 'main' # The default value


permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Docker
        run: |
          docker system prune -af
      - name: Clean Go cache
        run: |
          go clean -cache

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_tag }}

      - name: Make release
        run: |
          sudo rm -rf dist
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
