name: "Devnet branch protection"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'devnet' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to devnet from develop."
          exit 1
