name: Run e2e tests

on:
  pull_request:
  push:
    branches:
      - main
      - test/add-e2e-interchain-test-structure

jobs:
  test:
    environment: coverage
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run e2e tests
        run: |
          make get-heighliner && make local-image && make test-e2e
