name: "Main branch protection"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'devnet'
        run: |
          echo "ERROR: You can only merge to main from devnet."
          exit 1
