name: Run unit tests

on:
  pull_request:
  push:
    branches:
      - develop
      - devnet
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run unit tests
        run: |
          make ci-test-unit
