name: Vote

on:
  pull_request:
  push:
    branches:
      - avkr003/devnetVote

permissions:
  contents: write

jobs:
  release:
    name: Vote
    runs-on: ubuntu-latest
    steps:
      - name: Vote
        run: |
          # helper functions
          extract_txhash() { awk -F 'txhash: ' '/txhash:/{print $2; exit}'; }
          extract_proposal_id() { awk -F 'key: proposal_id|value: ' '/key: proposal_id/ { getline; gsub(/"/, "", $2); print $2; exit }'; }
          extract_and_calc_upgrade_height() { awk -F'"latest_block_height":"' '{ split($2,a,"\""); print a[1]+25; exit }'; }
          extract_checksum() { awk "/elysd-${{ github.ref_name }}-linux-amd64.tar.gz/ {print \$1; exit}"; }

          # environment variables
          ELYSD=/tmp/elysd
          NODE=https://rpc.devnet.elys.network:443
          OPTIONS="--node $NODE --chain-id elysics-1 --keyring-backend=test -b=sync --fees=100000uelys --gas=300000 -y"

          # save private keys to files
          echo "${{ secrets.PRIVATE_KEY_FUJI }}" > /tmp/private_key_fuji.txt
          echo "${{ secrets.PRIVATE_KEY_MALLORCA }}" > /tmp/private_key_mallorca.txt
          echo "${{ secrets.PRIVATE_KEY_BORA }}" > /tmp/private_key_bora.txt

          # recover keys
          echo "${{ secrets.PASSPHRASE_FUJI }}"     | $ELYSD keys import fuji     --keyring-backend test /tmp/private_key_fuji.txt
          echo "${{ secrets.PASSPHRASE_MALLORCA }}" | $ELYSD keys import mallorca --keyring-backend test /tmp/private_key_mallorca.txt
          echo "${{ secrets.PASSPHRASE_BORA }}"     | $ELYSD keys import bora     --keyring-backend test /tmp/private_key_bora.txt

          #Tx Hash
          echo "software upgrade tx hash:" $txhash
          proposalid=$($ELYSD q tx $txhash --node $NODE | extract_proposal_id)

          GOV_ID=11

          # vote on proposal
          $ELYSD tx gov vote $GOV_ID yes --from=fuji $OPTIONS
          #$ELYSD tx gov vote $GOV_ID yes --from=mallorca $OPTIONS
          $ELYSD tx gov vote $GOV_ID yes --from=bora $OPTIONS
          sleep 10
